

result = {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams",
    "@odata.count": 7,
    "value": [
        {
            "id": "f2a4d75b-549a-4867-87b4-66ded61e52ee",
            "createdDateTime": None,
            "displayName": "Digital Initiative Public Relations",
            "description": "Description of Digital Initiative Public Relations",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "c170c2e2-496d-4a64-8aa4-727de28b8315",
            "createdDateTime": None,
            "displayName": "MSFT",
            "description": "MSFT",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "2a7133bd-ecde-4666-9aa2-7ce9419d2bc3",
            "createdDateTime": None,
            "displayName": "Mark 8 Project Team",
            "description": "Welcome to the team that we've assembled to create the Mark 8.",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "6d1c3923-333d-4491-8e2c-b50727134b04",
            "createdDateTime": None,
            "displayName": "Retail",
            "description": "Description of Retail",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "16ba7b41-2960-48a6-9123-401e6a8160e1",
            "createdDateTime": None,
            "displayName": "Sales and Marketing",
            "description": "Description of Sales and Marketing",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "27c9fca0-a430-4066-b620-cf922778388b",
            "createdDateTime": None,
            "displayName": "U.S. Sales",
            "description": "Description of U.S. Sales",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        },
        {
            "id": "274a89f1-327a-4462-9511-da06e0d54723",
            "createdDateTime": None,
            "displayName": "MyGroup",
            "description": "Test group",
            "internalId": None,
            "classification": None,
            "specialization": None,
            "visibility": None,
            "webUrl": None,
            "isArchived": False,
            "tenantId": "2b8fcc74-1404-4f05-a2f9-2f5b64a94336",
            "isMembershipLimitedToOwners": None,
            "memberSettings": None,
            "guestSettings": None,
            "messagingSettings": None,
            "funSettings": None,
            "discoverySettings": None,
            "summary": None
        }
    ]
}
print(type(result))

values =